$font = GeistMono Nerd Font Mono

general {
    hide_cursor = true
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 1, linear
    animation = inputFieldDots, 1, 1, linear
}

background {
    monitor =
    path = /tmp/lock.png
}

# INPUT
input-field {
    monitor =
    size = 8%, 3%
    outline_thickness = 6
    inner_color = rgb(1c1c1c)

    outer_color = rgb(151515)
    check_color = rgb(d38c10)
    fail_color = rgb(d38c10)

    font_color = rgb(c0c0c0)
    fade_on_empty = false
    rounding = 9

    font_family = $font
    placeholder_text = 
    fail_text = 

    dots_size = 0.23
    dots_spacing = 0.3

    position = 0, 0
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME
    font_size = 70
    font_family = $font
    color = rgb(208fa3)

    position = 0, 380
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A %d %B"
    font_size = 15
    font_family = $font
    color = rgb(208fa3)

    position = 0, 325
    halign = center
    valign = center
}
